name: Continuous Integration 

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install meson build-essential git g++ libgtest-dev libgflags-dev
      - name: Setup Prerequisites
        run: bash ci/setup-prereq.sh
      - name: Build libdocument 
        run: |
            meson build -Dbuildtype=release --prefix=$HOME/local
            cd build
            ninja
      - name: Lint Checks 
        run: cd build && ninja lint
      - name: Formatting Checks 
        run: cd build && ninja clang-format-check 
